services:  
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - ${WP_VOLUME}:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - ${WP_VOLUME}:/var/www/html
    env_file :
      - .env
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    networks:
      - inception

  mariadb:
    image: mariadb
    container_name: mariadb
    env_file :
      - .env
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge